### model
model_name_or_path: models/qwen3-4b/full/sft
template: qwen3_nothink
trust_remote_code: true

### dataset
eval_dataset: alpaca_en_demo
cutoff_len: 2048
max_samples: 100
preprocessing_num_workers: 4

### output
output_dir: outputs/predictions/qwen3_full_sft
overwrite_output_dir: true

### eval
do_predict: true
per_device_eval_batch_size: 1
predict_with_generate: true
